-- 02_seed_crop_profiles.sql
-- Portable Wireless Soil Sensor Crop Recommendation Module
-- Seed 7 starter crop profiles with research agronomic ranges

INSERT INTO public.crop_reference_profiles (
    crop_name,
    scientific_name,
    ph_opt_min,
    ph_opt_max,
    temperature_opt_min_c,
    temperature_opt_max_c,
    ec_full_yield_max_dsm,
    ec_guidance_max_dsm,
    moisture_paw_min,
    moisture_paw_max,
    drainage_requirement,
    local_notes,
    source_urls,
    profile_version,
    active
) VALUES 
(
    'Mango',
    'Mangifera indica',
    5.5,
    7.5,
    24.0,
    30.0,
    NULL,
    4.0,
    50.0,
    80.0,
    'well drained and avoid waterlogging',
    'Mango thrives in deep, well-drained soils. Sensitive to waterlogging and severe salinity.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/mango/en/',
    'reference_v1',
    true
),
(
    'Rice',
    'Oryza sativa',
    5.5,
    7.0,
    20.0,
    30.0,
    3.0,
    3.0,
    75.0,
    100.0,
    'wet rice profile or saturated soil',
    'Rice is an aquatic/semi-aquatic crop requiring high soil moisture or flooding. Moderately tolerant to salinity.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/rice/en/',
    'reference_v1',
    true
),
(
    'Maize',
    'Zea mays',
    5.0,
    7.0,
    18.0,
    33.0,
    1.7,
    1.7,
    50.0,
    80.0,
    'well drained',
    'Maize requires well-aerated soils with good drainage. Sensitive to salinity levels above 1.7 dS/m.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/maize/en/',
    'reference_v1',
    true
),
(
    'Tomato',
    'Solanum lycopersicum',
    5.5,
    6.8,
    20.0,
    27.0,
    2.5,
    2.5,
    50.0,
    80.0,
    'well drained',
    'Tomato prefers slightly acidic, well-drained soils. Yield reduction begins when soil EC exceeds 2.5 dS/m.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/tomato/en/',
    'reference_v1',
    true
),
(
    'Chilli',
    'Capsicum annuum',
    5.5,
    6.8,
    17.0,
    30.0,
    1.5,
    1.5,
    50.0,
    80.0,
    'deep, fertile and well drained soil',
    'Chilli is sensitive to high salinity and waterlogging. Requires fertile, well-drained loam.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/pepper/en/',
    'reference_v1',
    true
),
(
    'Brinjal',
    'Solanum melongena',
    5.5,
    6.8,
    20.0,
    35.0,
    NULL,
    1.5,
    50.0,
    80.0,
    'well drained',
    'Brinjal requires warm temperatures and well-drained soil. Moderately sensitive to soil salinity.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/eggplant/en/',
    'reference_v1',
    true
),
(
    'Onion',
    'Allium cepa',
    6.0,
    7.0,
    12.0,
    25.0,
    1.2,
    1.2,
    50.0,
    75.0,
    'well drained sandy loam to sandy clay loam',
    'Onion requires friable, well-drained soil with pH near neutral. Highly sensitive to salinity above 1.2 dS/m.',
    'https://www.fao.org/land-water/databases-and-software/crop-information/onion/en/',
    'reference_v1',
    true
)
ON CONFLICT (crop_name) DO UPDATE SET
    scientific_name = EXCLUDED.scientific_name,
    ph_opt_min = EXCLUDED.ph_opt_min,
    ph_opt_max = EXCLUDED.ph_opt_max,
    temperature_opt_min_c = EXCLUDED.temperature_opt_min_c,
    temperature_opt_max_c = EXCLUDED.temperature_opt_max_c,
    ec_full_yield_max_dsm = EXCLUDED.ec_full_yield_max_dsm,
    ec_guidance_max_dsm = EXCLUDED.ec_guidance_max_dsm,
    moisture_paw_min = EXCLUDED.moisture_paw_min,
    moisture_paw_max = EXCLUDED.moisture_paw_max,
    drainage_requirement = EXCLUDED.drainage_requirement,
    local_notes = EXCLUDED.local_notes,
    source_urls = EXCLUDED.source_urls,
    profile_version = EXCLUDED.profile_version,
    active = EXCLUDED.active;
