-- ============================================================================
-- Reference schema for the AgriBot operational database (Supabase/Postgres).
--
-- This documents what is ALREADY LIVE in the project's Supabase instance, so
-- the app is reproducible from a fresh clone instead of only existing in one
-- hosted database. It is written to be safe to run against the live project
-- too: every statement is idempotent (CREATE ... IF NOT EXISTS / CREATE OR
-- REPLACE), so running it again is a no-op where the object already exists.
--
-- Run in the Supabase SQL editor before 01_system_alerts.sql and
-- 02_rain_prediction_enabled.sql.
-- ============================================================================

-- ── user_accounts ────────────────────────────────────────────────────────────
create table if not exists public.user_accounts (
  id bigint generated by default as identity not null,
  username character varying(50) not null,
  email character varying(255) not null,
  user_password_hash text not null,
  system_control_password_hash text not null,
  account_status character varying(20) not null default 'active'::character varying,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  phone character varying(20) null,
  constraint user_accounts_pkey primary key (id),
  constraint user_accounts_email_key unique (email),
  constraint user_accounts_username_key unique (username),
  constraint user_accounts_account_status_check check (
    (account_status)::text = any (
      (array['active'::character varying, 'disabled'::character varying])::text[]
    )
  )
);

-- ── system_switches ──────────────────────────────────────────────────────────
create table if not exists public.system_switches (
  device_id text not null,
  pump_water boolean not null default false,
  pump_nitrogen boolean not null default false,
  pump_phosphorus boolean not null default false,
  pump_potassium boolean not null default false,
  updated_at timestamp with time zone null default now(),
  system_switch boolean not null default false,
  light_01 boolean not null default false,
  light_02 boolean not null default false,
  constraint system_switches_pkey primary key (device_id)
);

-- ── soil_readings (raw legacy time-series) ──────────────────────────────────
create table if not exists public.soil_readings (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  device_id text not null,
  source text not null,
  packet_format text not null,
  battery_status text not null,
  battery_voltage double precision not null,
  receiver_wifi_connected boolean not null,
  receiver_wifi_signal_strength_dbm integer not null,
  receiver_wifi_signal_quality text not null,
  hc12_packet_received boolean not null default true,
  hc12_signal_strength_available boolean not null default false,
  soil_moisture_percent double precision not null,
  soil_temperature_celsius double precision not null,
  ec_levels integer not null,
  soil_ph double precision not null,
  nitrogen integer not null,
  phosphorus integer not null,
  potassium integer not null,
  salinity integer not null,
  tds_mg_l integer not null,
  received_uptime_ms bigint not null,
  constraint soil_readings_pkey primary key (id)
);

create index if not exists soil_readings_created_at_index
  on public.soil_readings using btree (created_at desc);

-- ── latest_soil_reading (one row per device, upserted) ──────────────────────
create table if not exists public.latest_soil_reading (
  device_id text not null,
  updated_at timestamp with time zone not null default now(),
  source text not null,
  packet_format text not null,
  battery_status text not null,
  battery_voltage double precision not null,
  receiver_wifi_connected boolean not null,
  receiver_wifi_signal_strength_dbm integer not null,
  receiver_wifi_signal_quality text not null,
  hc12_packet_received boolean not null default true,
  hc12_signal_strength_available boolean not null default false,
  soil_moisture_percent double precision not null,
  soil_temperature_celsius double precision not null,
  ec_levels integer not null,
  soil_ph double precision not null,
  nitrogen integer not null,
  phosphorus integer not null,
  potassium integer not null,
  salinity integer not null,
  tds_mg_l integer not null,
  sensor_status text not null default 'Disconnected'::text,
  receiver_uptime_minutes bigint not null default 0,
  receiver_uptime_seconds integer not null default 0,
  constraint latest_soil_reading_pkey primary key (device_id)
);

create or replace function public.update_latest_reading_time()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists latest_reading_updated_at on public.latest_soil_reading;
create trigger latest_reading_updated_at
  before update on public.latest_soil_reading
  for each row
  execute function public.update_latest_reading_time();

-- ── soil_sensor_readings (dashboard time-series) ────────────────────────────
create table if not exists public.soil_sensor_readings (
  id uuid not null default gen_random_uuid(),
  device_id text not null,
  soil_moisture_percent double precision not null,
  soil_temperature_celsius double precision not null,
  conductivity integer not null,
  soil_ph double precision not null,
  nitrogen integer not null,
  phosphorus integer not null,
  potassium integer not null,
  salinity integer not null,
  tds_mg_l integer not null,
  created_at timestamp with time zone not null default now(),
  constraint soil_sensor_readings_pkey primary key (id)
);

-- ── environment_sensor_readings (weather station) ───────────────────────────
create table if not exists public.environment_sensor_readings (
  id bigint generated by default as identity not null,
  device_id text not null,
  recorded_at timestamp with time zone not null default now(),
  light_intensity_lux double precision null,
  light_condition text null,
  bmp_temperature_c double precision null,
  altitude_m double precision null,
  soil_temperature_c double precision null,
  air_temperature_c double precision null,
  humidity_percent double precision null,
  heat_index_c double precision null,
  dew_point_c double precision null,
  soil_condition text null,
  dew_point_spread_c double precision null,
  condensation_risk text null,
  atmospheric_pressure_hpa double precision null,
  air_comfort text null,
  soil_vs_air text null,
  pressure_condition text null,
  rain_analog_raw integer null,
  rain_digital_value smallint null,
  rain_wetness_percent integer null,
  rain_detected boolean null,
  rain_status text null,
  rain_condition text null,
  wifi_rssi_dbm integer null,
  esp32_uptime_ms bigint null,
  constraint environment_sensor_readings_pkey primary key (id),
  constraint environment_sensor_readings_humidity_percent_check check (
    humidity_percent is null or (humidity_percent >= 0 and humidity_percent <= 100)
  ),
  constraint environment_sensor_readings_rain_analog_raw_check check (
    rain_analog_raw is null or (rain_analog_raw >= 0 and rain_analog_raw <= 4095)
  ),
  constraint environment_sensor_readings_rain_digital_value_check check (
    rain_digital_value is null or rain_digital_value = any (array[0, 1])
  ),
  constraint environment_sensor_readings_rain_wetness_percent_check check (
    rain_wetness_percent is null or (rain_wetness_percent >= 0 and rain_wetness_percent <= 100)
  )
);

create index if not exists idx_environment_readings_recorded_at
  on public.environment_sensor_readings using btree (recorded_at desc);
create index if not exists idx_environment_readings_device
  on public.environment_sensor_readings using btree (device_id, recorded_at desc);

-- ── pump_activation_logs ─────────────────────────────────────────────────────
create table if not exists public.pump_activation_logs (
  session_id text not null,
  device_id text not null,
  pump_name text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone null,
  duration_seconds bigint null,
  status text not null default 'running'::text,
  created_at timestamp with time zone not null default now(),
  constraint pump_activation_logs_pkey primary key (session_id),
  constraint pump_activation_logs_pump_name_check check (
    pump_name = any (array['water'::text, 'nitrogen'::text, 'phosphorus'::text, 'potassium'::text])
  ),
  constraint pump_activation_logs_status_check check (
    status = any (array['running'::text, 'completed'::text])
  )
);

-- ── rain_predictions (extended by 02_rain_prediction_enabled.sql) ──────────
create table if not exists public.rain_predictions (
  device_id text not null,
  will_rain boolean not null,
  updated_at timestamp with time zone null default now(),
  constraint rain_predictions_pkey primary key (device_id)
);

-- ── ai_chat_history ──────────────────────────────────────────────────────────
create table if not exists public.ai_chat_history (
  id uuid not null default gen_random_uuid(),
  session_id text not null,
  role text not null,
  content text not null,
  created_at timestamp with time zone not null default now(),
  constraint ai_chat_history_pkey primary key (id),
  constraint ai_chat_history_role_check check (role = any (array['user'::text, 'assistant'::text]))
);

create index if not exists idx_ai_chat_history_session
  on public.ai_chat_history using btree (session_id, created_at);

-- ── "Wireless sensor Soil Analysis data" (farmer-labeled samples) ──────────
create table if not exists public."Wireless sensor Soil Analysis data" (
  id uuid not null default gen_random_uuid(),
  saved_at timestamp with time zone not null default now(),
  soil_sample_label text not null,
  soil_moisture double precision not null,
  temperature double precision not null,
  soil_ph double precision not null,
  soil_conductivity double precision not null,
  soil_health_score integer null,
  nitrogen integer null,
  phosphorus integer null,
  potassium integer null,
  tds double precision null,
  salinity double precision null,
  recommended_crop text null,
  recommendation_reason text null,
  device_id text not null default 'agribot_receiver_01'::text,
  crop_label text null,
  reading_at timestamp with time zone null,
  prediction_confidence double precision null,
  model_version text null,
  label_status text not null default 'pending'::text,
  labelled_by text null,
  verified_by text null,
  verified_at timestamp with time zone null,
  constraint wireless_soil_analysis_pkey primary key (id),
  constraint valid_soil_health_score check (
    soil_health_score is null or (soil_health_score >= 0 and soil_health_score <= 100)
  ),
  constraint valid_wireless_crop_label check (
    crop_label is null or char_length(trim(both from crop_label)) > 0
  ),
  constraint valid_wireless_label_status check (
    label_status = any (array['pending'::text, 'verified'::text, 'rejected'::text])
  ),
  constraint valid_wireless_nitrogen check (nitrogen is null or nitrogen >= 0),
  constraint valid_wireless_phosphorus check (phosphorus is null or phosphorus >= 0),
  constraint valid_wireless_potassium check (potassium is null or potassium >= 0),
  constraint valid_wireless_prediction_confidence check (
    prediction_confidence is null or (prediction_confidence >= 0 and prediction_confidence <= 100)
  ),
  constraint valid_wireless_salinity check (salinity is null or salinity >= 0),
  constraint valid_wireless_soil_conductivity check (soil_conductivity >= 0),
  constraint valid_wireless_soil_moisture check (soil_moisture >= 0 and soil_moisture <= 100),
  constraint valid_wireless_soil_ph check (soil_ph >= 0 and soil_ph <= 14),
  constraint valid_wireless_soil_sample_label check (char_length(trim(both from soil_sample_label)) > 0),
  constraint valid_wireless_tds check (tds is null or tds >= 0)
);

create index if not exists wireless_soil_analysis_crop_label_index
  on public."Wireless sensor Soil Analysis data" using btree (crop_label);
create index if not exists wireless_soil_analysis_saved_at_index
  on public."Wireless sensor Soil Analysis data" using btree (saved_at desc);
create index if not exists wireless_soil_analysis_label_status_index
  on public."Wireless sensor Soil Analysis data" using btree (label_status);
create index if not exists wireless_soil_analysis_device_saved_index
  on public."Wireless sensor Soil Analysis data" using btree (device_id, saved_at desc);
create index if not exists wireless_soil_analysis_verified_training_index
  on public."Wireless sensor Soil Analysis data" using btree (crop_label, saved_at desc)
  where (label_status = 'verified'::text);
create unique index if not exists wireless_soil_unique_reading_crop_index
  on public."Wireless sensor Soil Analysis data" using btree (device_id, reading_at, crop_label)
  where (reading_at is not null and crop_label is not null);

create or replace function public.set_soil_label_verification_time()
returns trigger
language plpgsql
as $$
begin
  if new.label_status = 'verified' and (old.label_status is distinct from 'verified') then
    new.verified_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists set_soil_label_verification_time_trigger on public."Wireless sensor Soil Analysis data";
create trigger set_soil_label_verification_time_trigger
  before update of label_status on public."Wireless sensor Soil Analysis data"
  for each row
  execute function public.set_soil_label_verification_time();
